-- [home](index.html) :: [about](about.html) :: [github](http://github.com/timm/lua) :: [discuss](http://github.com/timm/lua/issues) :: [&copy; 2020](https://github.com/timm/lua/blob/master/LICENSE.md) by [timm](http://menzies.us)

--
-- Just a little light Lua. 
-- Less is more. Less is best.
-- 
-- "He was glad that he liked the country undecorated, hard, and stripped of its finery. He had got down to the bare bones of it, and they were fine and strong and simple." -- [M. Ole](https://www.gutenberg.org/files/289/289-h/289-h.htm#link2H_4_0004)
--
-- Useful  for training graduate students in software analytics. "Here, take this executable
-- specification and code it up in e.g. Python."
--
